#!/usr/bin/env ruby
require 'JohnPaulIII_palindrome'
require 'open-uri'

lines = URI.open('https://cdn.learnenough.com/phrases.txt').readlines
lines.each do |line|
  if line.palindrome?
    puts "palindrome detected: #{line}"
  end
end

palindromes = lines.select(&:palindrome?)
File.write('palindromes_url.txt', palindromes.join)